// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMO7puc7nqbYGKtx3sAFBmmoYt9ny5kQQ',
    appId: '1:444002551694:web:d824d5517c2f6b196f86df',
    messagingSenderId: '444002551694',
    projectId: 'fir-64a59',
    authDomain: 'fir-64a59.firebaseapp.com',
    databaseURL: 'https://fir-64a59-default-rtdb.firebaseio.com',
    storageBucket: 'fir-64a59.firebasestorage.app',
    measurementId: 'G-48ZNRYV53W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApx8rAO05tmnKVgJ7cenwi3fE_q83avFg',
    appId: '1:444002551694:android:c63f0a9e5f20d2946f86df',
    messagingSenderId: '444002551694',
    projectId: 'fir-64a59',
    databaseURL: 'https://fir-64a59-default-rtdb.firebaseio.com',
    storageBucket: 'fir-64a59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwlnBiBl67DgULIYB0wMbYetcsAFnmCLE',
    appId: '1:444002551694:ios:2611e5f65c0526616f86df',
    messagingSenderId: '444002551694',
    projectId: 'fir-64a59',
    databaseURL: 'https://fir-64a59-default-rtdb.firebaseio.com',
    storageBucket: 'fir-64a59.firebasestorage.app',
    iosBundleId: 'com.example.hired',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwlnBiBl67DgULIYB0wMbYetcsAFnmCLE',
    appId: '1:444002551694:ios:2611e5f65c0526616f86df',
    messagingSenderId: '444002551694',
    projectId: 'fir-64a59',
    databaseURL: 'https://fir-64a59-default-rtdb.firebaseio.com',
    storageBucket: 'fir-64a59.firebasestorage.app',
    iosBundleId: 'com.example.hired',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMO7puc7nqbYGKtx3sAFBmmoYt9ny5kQQ',
    appId: '1:444002551694:web:21dd14e154b047b76f86df',
    messagingSenderId: '444002551694',
    projectId: 'fir-64a59',
    authDomain: 'fir-64a59.firebaseapp.com',
    databaseURL: 'https://fir-64a59-default-rtdb.firebaseio.com',
    storageBucket: 'fir-64a59.firebasestorage.app',
    measurementId: 'G-R6FL74WY5Z',
  );
}
