import 'package:get/get_navigation/src/root/internacionalization.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'welcome_back': 'Welcome Back!',
      'register_subtitle': 'Register to start your job search journey',
      'email': 'Email',
      'enter_email': 'Enter your email',
      'password': 'Password',
      'enter_password': 'Enter your password',
      'email_required': 'Please enter your email',
      'invalid_email': 'Please enter a valid email address',
      'password_required': 'Please enter your password',
      'short_password': 'Password must be at least 6 characters',
      'forgot_password': 'Forgot Password?',
      'already_account': 'Already have an account?',
      'sign_up': 'Sign Up',
      'login': 'Login',
      'job_home_title': 'Job Opportunities',
      'search_jobs': 'Search for jobs',
      'apply_now': 'Apply Now',
      'job_type': 'Type',
      'location': 'Location',
      'full_time': 'Full-Time',
      'part_time': 'Part-Time',
      'remote': 'Remote',
      'language': 'Language',
    },
    'es_ES': {
      'welcome_back': '¡Bienvenido de nuevo!',
      'register_subtitle': 'Regístrese para comenzar su búsqueda de trabajo',
      'email': 'Correo electrónico',
      'enter_email': 'Ingrese su correo electrónico',
      'password': 'Contraseña',
      'enter_password': 'Ingrese su contraseña',
      'email_required': 'Por favor, ingrese su correo electrónico',
      'invalid_email': 'Por favor, ingrese un correo electrónico válido',
      'password_required': 'Por favor, ingrese su contraseña',
      'short_password': 'La contraseña debe tener al menos 6 caracteres',
      'forgot_password': '¿Olvidaste tu contraseña?',
      'already_account': '¿Ya tienes una cuenta?',
      'sign_up': 'Regístrate',
      'login': 'Iniciar sesión',
      'job_home_title': 'Oportunidades de trabajo',
      'search_jobs': 'Buscar trabajos',
      'apply_now': 'Aplica ahora',
      'job_type': 'Tipo',
      'location': 'Ubicación',
      'full_time': 'Tiempo completo',
      'part_time': 'Medio tiempo',
      'remote': 'Remoto',
      'language': 'Idioma',
    },
    'hi_IN': {
      'welcome_back': 'वापसी पर स्वागत है!',
      'register_subtitle':
          'अपनी नौकरी खोज यात्रा शुरू करने के लिए पंजीकरण करें',
      'email': 'ईमेल',
      'enter_email': 'अपना ईमेल दर्ज करें',
      'password': 'पासवर्ड',
      'enter_password': 'अपना पासवर्ड दर्ज करें',
      'email_required': 'कृपया अपना ईमेल दर्ज करें',
      'invalid_email': 'कृपया एक वैध ईमेल पता दर्ज करें',
      'password_required': 'कृपया अपना पासवर्ड दर्ज करें',
      'short_password': 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए',
      'forgot_password': 'पासवर्ड भूल गए?',
      'already_account': 'पहले से एक खाता है?',
      'sign_up': 'साइन अप करें',
      'login': 'लॉग इन करें',
      'job_home_title': 'नौकरी के अवसर',
      'search_jobs': 'नौकरियों के लिए खोजें',
      'apply_now': 'अभी आवेदन करें',
      'job_type': 'प्रकार',
      'location': 'स्थान',
      'full_time': 'पूर्णकालिक',
      'part_time': 'आंशिककालिक',
      'remote': 'रिमोट',
      'language': 'भाषा',
    },
  };
}
